name: CodeSee

on:
    workflow_call:
        secrets:
            CODESEE_ARCH_DIAG_API_TOKEN:
                required: true

defaults:
    run:
        shell: bash

env:
    CI: true

permissions:
    contents: read
    pull-requests: write

jobs:
    codesee:
        runs-on: macos-14
        continue-on-error: true
        timeout-minutes: 1
        steps:
            # https://github.com/Codesee-io/codesee-action
            - uses: Codesee-io/codesee-action@v2
              with:
                  codesee-token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
                  codesee-url: https://app.codesee.io
