name: markdownlint

on:
    workflow_call:
    workflow_dispatch:

defaults:
    run:
        shell: bash

env:
    CI: true

permissions:
    contents: read
    pull-requests: read

jobs:
    markdownlint:
        runs-on: macos-14
        timeout-minutes: 1
        steps:
            # https://github.com/actions/checkout
            - uses: actions/checkout@v4

            # https://nodejs.org/api/corepack.html
            - name: Enable corepack (for pnpm)
              run: corepack enable

            - name: Setup the latest Node.js LTS version
              # https://github.com/actions/setup-node
              uses: actions/setup-node@v4
              with:
                  cache: pnpm
                  node-version: lts/*

            - name: Install Node.js dependencies with pnpm
              # https://pnpm.io/cli/install
              run: >
                  pnpm install
                  --frozen-lockfile

            # https://github.com/marketplace/actions/markdownlint-cli2-action
            - uses: DavidAnson/markdownlint-cli2-action@v15
              with:
                  globs: |
                      *.md
                      !.github/TECHSTACK.md
